# This is a basic workflow to help you get started with Actions

name: Greeting from Xian Yi Fan

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    my-jobs: 
      
      name: My Job

      runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Runs a single command using the runners shell
      - name: Print a greeting!
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Yi Fan
          LAST_NAME: Xian

      # Runs a set of commands using the runners shell
        run: |
          echo $MY_VAR $LAST_NAME $FIRST_NAME.
